source 'https://rubygems.org'
group :jekyll_plugins do
    gem 'classifier-reborn'
    gem 'jekyll'
    gem 'jekyll-archives'
    gem 'jekyll-diagrams'
    gem 'jekyll-email-protect'
    gem 'jekyll-feed'
    gem 'jekyll-get-json'
    gem 'jekyll-imagemagick'
    gem 'jekyll-jupyter-notebook'
    gem 'jekyll-link-attributes'
    gem 'jekyll-minifier'
    gem 'jekyll-paginate-v2'
    gem 'jekyll-scholar'
    gem 'jekyll-sitemap'
    gem 'jekyll-toc'
    gem 'jekyll-twitter-plugin'
    gem 'jemoji'
    gem 'mini_racer'
    gem 'unicode_utils'
    gem 'webrick'
    gem 'jekyll-seo-tag', '~> 2.6'
    gem 'jekyll-paginate', '~> 1.1'
    gem 'jekyll-gist', '~> 1.5'
    gem 'jekyll-github-metadata', '~> 2.13'
    gem 'jekyll-remote-theme', '~> 0.4.2'
    gem 'jekyll-mentions', '~> 1.6'
    gem 'jekyll-redirect-from', '~> 0.16'
    gem 'jekyll-optional-front-matter', '~> 0.3'
    gem 'jekyll-readme-index', '~> 0.3'
    gem 'jekyll-default-layout', '~> 0.1'
    gem 'jekyll-titles-from-headings', '~> 0.5'
    gem 'jekyll-swiss', '1.0.0' # Update to be compatible with github-pages
    gem 'jekyll-theme-primer', '~> 0.5'
    gem 'jekyll-theme-hacker', '~> 0.1'
    gem 'jekyll-theme-cayman', '~> 0.1'
    gem 'jekyll-theme-dinky', '~> 0.1'
    gem 'jekyll-theme-architect', '~> 0.1'
    gem 'jekyll-theme-leap-day', '~> 0.1'
    gem 'jekyll-theme-merlot', '~> 0.1'
    gem 'jekyll-theme-midnight', '~> 0.1'
    gem 'jekyll-theme-minimal', '~> 0.1'
    gem 'jekyll-theme-modernist', '~> 0.1'
    gem 'jekyll-theme-slate', '~> 0.1'
    gem 'jekyll-theme-tactile', '~> 0.1'
    gem 'jekyll-theme-time-machine', '~> 0.1'
    gem 'jekyll-coffeescript', '~> 1.0'
    gem 'jekyll-sass-converter', '1.5.2' # Use the version required by github-pages
    gem 'jekyll-watch', '~> 2.0'
    gem 'kramdown', '~> 2.3' # Update to be compatible with kramdown-parser-gfm
    gem 'kramdown-parser-gfm', '~> 1.1'
    gem 'liquid', '~> 4.0' # Update to be compatible with jekyll-remote-theme
    gem 'rouge', '~> 3.0'
    gem 'github-pages', '~> 227' # Ensure compatibility with other gems
end
group :other_plugins do
    gem 'feedjira'
    gem 'httparty'
end
